FROM nginx

COPY /dist/project-manager /usr/share/nginx/html

#CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/config/config.tmpl.json > /usr/share/nginx/html/assets/config/config.tmpl.json"]
